### ISSUE TITLE
Command list in readme incorrect

### ISSUE THREAD

**Issue by O1LER** [vulcan-dev/BeamMP-FloodMod#11]
The commands listed in the readme page are incorrect, the code uses these commands as of v1.0.1

`/flood_start` - Starts the flood
`/flood_stop` - Stops the flood
`/flood_reset` - Resets the height and disables the flood
`/flood_resetAt` - Set the reset level to a certain height
`/flood_rainAmount` - Set the amount of rain
`/flood_rainVolume` - Set the volume (loudnes?) of rain
`/flood_floodWithRain` - Enable/Disable rain while flooding (Yes thats the actual command, you might get rid of the double flood in it while at it)
`/flood_level` <level> - Sets the flood level/height
`/flood_speed` <speed> - Sets the flood speed (0.001 is default)
`/flood_decrease` <decrease> - Makes the water level decrease instead of increase
`/flood_limit` <limit> - Sets the flood height limit
`/flood_limitEnabled` <enabled> - Enables or disables the flood height limit
`/flood_printSettings` - Prints the current flood settings

**Comment by daniel-w0** [comment]
I have updated the README so it works with both versions, thank you for letting me know :)
