### ISSUE TITLE
Cant get the mod to work

### ISSUE THREAD

**Issue by Marcus369** [vulcan-dev/BeamMP-FloodMod#3]
![image](https://github.com/vulcan-dev/BeamMP-FloodMod/assets/31628261/6941f4f0-1bc6-4ebe-88b4-f8f92b87fa66)

Not sure why its not working but commands dont work in the game chat and im guessing it has to do with these warnings

**Comment by PascalOtto** [comment]
got the same problem

**Comment by BurnhamR** [comment]
I am getting this error as well, Any idea how to resolve it?

**Comment by Marcus369** [comment]
update your server from beammp website, turned out i just had an old
version of the server

**Comment by BurnhamR** [comment]
Yup, That was my issue as well.
Thank you!
