### ISSUE TITLE
Every map doesn't have an "ocean"

### ISSUE THREAD

**Issue by ekaingamersTTV** [vulcan-dev/BeamMP-FloodMod#4]
trying it on my server, every map that has water surrounding on all sides including small island, west coast usa, and flood escape crater

**Comment by ekaingamersTTV** [comment]
![image](https://github.com/vulcan-dev/BeamMP-FloodMod/assets/125496299/497e7342-481a-4a35-8fd1-2952e3daa29c)

**Comment by ekaingamersTTV** [comment]
vanilla map

**Comment by daniel-w0** [comment]
Let me know if you experience this again, going to close the issue for now as it works for me and I'm about to make a little update
