### ISSUE TITLE
[NOT AN ISSUE] Discussion

### ISSUE THREAD

**Issue by RighteousRyan1** [vulcan-dev/BeamMP-FloodMod#6]
I've been wanting to get into BeamNG modding in general- what IDEs/libs (dependencies)/documentation should I look at/use and how do I set it up to work ingame? YouTube isn't very much help when it comes to mods outside of vehicles and the sort.

**Comment by daniel-w0** [comment]
There's not much to go off in terms of modding with Lua.
The best thing to do is just look through the game scripts and mods on Github or the forums.

And I just use Visual Studio Code for Lua, it works quite well
