### ISSUE TITLE
Italy: No Ocean found

### ISSUE THREAD

**Issue by 20Bosko07** [vulcan-dev/BeamMP-FloodMod#7]
Hey!
Very nice MOD. But I have this error when start the flood with **/flood_start** on vanilla Italy Map:
**[22/02/24` 11:42:04] [LUA] This map doesn't have an ocean, unable to flood**

Can someone help?

**Comment by daniel-w0** [comment]
Have you joined the server? The way I've done it is that it requires at least one person to join the server for it to actually get the ocean since there's no way for the server to communicate directly with the game

**Comment by 20Bosko07** [comment]
Good to know. Thank you so much. I look later if it works. Thanks.
Good Day.

**Comment by 20Bosko07** [comment]
Working well. Thank you!
